name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.19

  test:
    name: Test setup-postgresql
    runs-on: ${{ matrix.platform }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.platform }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ubuntu-20.04, macos-latest, macos-11, macos-13, windows-latest, windows-2019]
        postgresql_version: [10, 11, 12, 14, 15]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run setup-postgresql
        uses: ./
        with:
          postgresql_version: ${{ matrix.postgresql_version }}
